---
# Copyright Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Import SSH key rotation setup and backup tasks
  ansible.builtin.import_tasks: backup.yml

- name: Import SSH key rotation copy tasks
  ansible.builtin.import_tasks: copy_keys.yml

- name: Import SSH key rotation update tasks
  ansible.builtin.import_tasks: update.yml

- name: Import SSH key rotation cleanup tasks
  ansible.builtin.import_tasks: cleanup.yml
  when: edpm_ssh_key_rotation_cleanup_backups | bool
